# Generated by Django 3.2 on 2021-04-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='sub_admin_assigned',
            new_name='assigned_admin',
        ),
    ]
